### ISSUE TITLE
"If anyone registered" system error

### ISSUE THREAD

**Issue by Zsoz25K** [Kissadere/authme-register-system#1]
If i register this error shows:
_Warning: mysqli_num_rows() expects parameter 1 to be mysqli_result, bool given in C:\xampp\htdocs\index.php on line 73_

Thank you in advance for your help!

**Comment by Kissadere** [comment]
Hello. I'll try to help you solve this issue.

I need to get some extra information to determine why are you getting that error.
First things first. What's your php version?

Also, this script uses CUSTOM field names for AuthMe, so make sure to change them to your AuthMe default or custom field names.

**Comment by Zsoz25K** [comment]
Hi! I use PHP 7.4.8. And i use a empty database.

**Comment by Kissadere** [comment]
Can you please print the structure of your database so i can lookup if there's anything wrong with it?. Thanks in advanced.

**Comment by Zsoz25K** [comment]
How can i print my database structure?
